## Exploring the Neighbourhoods

Some exploration of the venue categories of the neighbourhoods is done in the following cells.

In [1]:
# Third party libraries
import pandas as pd # Data structures

In [2]:
toronto_venues_500  = pd.read_csv('toronto_venues_500.csv')
toronto_venues_1000 = pd.read_csv('toronto_venues_1000.csv')
toronto_venues_2000 = pd.read_csv('toronto_venues_2000.csv')

In [6]:
print('{} Venues within 500 metres of Neighbourhood centres'.format(toronto_venues_500.sum()[1:].sum()))
print('{} Venues within 1000 metres of Neighbourhood centres'.format(toronto_venues_1000.sum()[1:].sum()))
print('{} Venues within 2000 metres of Neighbourhood centres'.format(toronto_venues_2000.sum()[1:].sum()))

1602 Venues within 500 metres of Neighbourhood centres
3175 Venues within 1000 metres of Neighbourhood centres
3867 Venues within 2000 metres of Neighbourhood centres

In [7]:
pd.DataFrame([toronto_venues_500.Neighbourhood, toronto_venues_500.sum(axis=1)],
             index = ['Neighbourhood','Venues']).T.sort_values(
                by = 'Venues', ascending = False)

                                        Neighbourhood Venues
37           Toronto Dominion Centre, Design Exchange    100
7                      Commerce Court, Victoria Hotel    100
11             First Canadian Place, Underground city    100
13                           Garden District, Ryerson    100
14  Harbourfront East, Union Station, Toronto Islands    100
31                                     Stn A PO Boxes     99
25                           Richmond, Adelaide, King     95
29                                     St. James Town     80
6                                Church and Wellesley     75
17          Kensington Market, Chinatown, Grange Park     63
4                                  Central Bay Street     59
0                                         Berczy Park     58
30                        St. James Town, Cabbagetown     47
24                          Regent Park, Harbourfront     47
36                       The Danforth West, Riverdale     43
19                           Little Portugal, Trinity     42
32                                    Studio District     36
28                                 Runnymede, Swansea     34
38                     University of Toronto, Harbord     32
8                                          Davisville     32
23        Queen's Park, Ontario Provincial Government     30
15                      High Park, The Junction South     25
1        Brockton, Parkdale Village, Exhibition Place     24
34                The Annex, North Midtown, Yorkville     21
16                     India Bazaar, The Beaches West     21
21                  North Toronto West, Lawrence Park     19
2   Business reply mail Processing Centre, South C...     17
10                       Dufferin, Dovercourt Village     15
5                                            Christie     15
3   CN Tower, King and Spadina, Railway Lands, Har...     15
22                             Parkdale, Roncesvalles     14
33  Summerhill West, Rathnelly, South Hill, Forest...     14
9                                    Davisville North      8
35                                        The Beaches      5
26                                           Rosedale      4
12    Forest Hill North & West, Forest Hill Road Park      4
20                        Moore Park, Summerhill East      3
18                                      Lawrence Park      3
27                                           Roselawn      3

In [8]:
pd.DataFrame([toronto_venues_1000.Neighbourhood, toronto_venues_1000.sum(axis=1)],
             index = ['Neighbourhood','Venues']).T.sort_values(
                by = 'Venues', ascending = False)

                                        Neighbourhood Venues
0                                         Berczy Park    100
15                      High Park, The Junction South    100
37           Toronto Dominion Centre, Design Exchange    100
36                       The Danforth West, Riverdale    100
34                The Annex, North Midtown, Yorkville    100
32                                    Studio District    100
31                                     Stn A PO Boxes    100
29                                     St. James Town    100
25                           Richmond, Adelaide, King    100
24                          Regent Park, Harbourfront    100
23        Queen's Park, Ontario Provincial Government    100
22                             Parkdale, Roncesvalles    100
1        Brockton, Parkdale Village, Exhibition Place    100
17          Kensington Market, Chinatown, Grange Park    100
19                           Little Portugal, Trinity    100
14  Harbourfront East, Union Station, Toronto Islands    100
9                                    Davisville North    100
4                                  Central Bay Street    100
5                                            Christie    100
6                                Church and Wellesley    100
7                      Commerce Court, Victoria Hotel    100
8                                          Davisville    100
38                     University of Toronto, Harbord    100
11             First Canadian Place, Underground city    100
13                           Garden District, Ryerson    100
35                                        The Beaches     79
16                     India Bazaar, The Beaches West     77
28                                 Runnymede, Swansea     76
33  Summerhill West, Rathnelly, South Hill, Forest...     73
10                       Dufferin, Dovercourt Village     69
20                        Moore Park, Summerhill East     60
2   Business reply mail Processing Centre, South C...     48
12    Forest Hill North & West, Forest Hill Road Park     47
21                  North Toronto West, Lawrence Park     45
30                        St. James Town, Cabbagetown     34
27                                           Roselawn     22
26                                           Rosedale     21
3   CN Tower, King and Spadina, Railway Lands, Har...     15
18                                      Lawrence Park      9

In [9]:
pd.DataFrame([toronto_venues_2000.Neighbourhood, toronto_venues_2000.sum(axis=1)],
             index = ['Neighbourhood','Venues']).T.sort_values(
                by = 'Venues', ascending = False)

                                        Neighbourhood Venues
0                                         Berczy Park    100
29                                     St. James Town    100
22                             Parkdale, Roncesvalles    100
23        Queen's Park, Ontario Provincial Government    100
24                          Regent Park, Harbourfront    100
25                           Richmond, Adelaide, King    100
26                                           Rosedale    100
27                                           Roselawn    100
28                                 Runnymede, Swansea    100
30                        St. James Town, Cabbagetown    100
20                        Moore Park, Summerhill East    100
31                                     Stn A PO Boxes    100
32                                    Studio District    100
33  Summerhill West, Rathnelly, South Hill, Forest...    100
34                The Annex, North Midtown, Yorkville    100
35                                        The Beaches    100
36                       The Danforth West, Riverdale    100
37           Toronto Dominion Centre, Design Exchange    100
21                  North Toronto West, Lawrence Park    100
19                           Little Portugal, Trinity    100
1        Brockton, Parkdale Village, Exhibition Place    100
9                                    Davisville North    100
2   Business reply mail Processing Centre, South C...    100
3   CN Tower, King and Spadina, Railway Lands, Har...    100
4                                  Central Bay Street    100
5                                            Christie    100
6                                Church and Wellesley    100
7                      Commerce Court, Victoria Hotel    100
8                                          Davisville    100
38                     University of Toronto, Harbord    100
11             First Canadian Place, Underground city    100
12    Forest Hill North & West, Forest Hill Road Park    100
13                           Garden District, Ryerson    100
14  Harbourfront East, Union Station, Toronto Islands    100
15                      High Park, The Junction South    100
16                     India Bazaar, The Beaches West    100
17          Kensington Market, Chinatown, Grange Park    100
18                                      Lawrence Park     87
10                       Dufferin, Dovercourt Village     80

In [10]:
toronto_venues_1000

,Neighbourhood,Arts & Entertainment,College & University,Food,Nightlife Spot,Outdoors & Recreation,Professional & Other Places,Residence,Shop & Service,Travel & Transport
0,Berczy Park,5,0,50,8,14,1,0,15,7
1,"Brockton, Parkdale Village, Exhibition Place",9,0,49,10,9,2,0,20,1
2,"Business reply mail Processing Centre, South C...",0,0,26,5,8,0,0,9,0
3,"CN Tower, King and Spadina, Railway Lands, Har...",1,0,4,0,8,0,0,0,2
4,Central Bay Street,10,1,52,8,5,1,0,18,5
5,Christie,4,0,62,11,6,1,0,15,1
6,Church and Wellesley,4,0,58,5,6,2,0,20,5
7,"Commerce Court, Victoria Hotel",15,0,46,5,10,1,0,14,9
8,Davisville,2,0,64,6,8,0,1,17,2
9,Davisville North,3,0,60,4,9,0,0,23,1
10,"Dufferin, Dovercourt Village",2,1,31,5,12,0,0,18,0
11,"First Canadian Place, Underground city",16,0,44,5,10,1,0,14,10
12,"Forest Hill North & West, Forest Hill Road Park",0,0,27,0,12,0,0,8,0
13,"Garden District, Ryerson",11,0,60,4,8,1,0,12,4
14,"Harbourfront East, Union Station, Toronto Islands",12,0,43,9,17,2,0,7,10
15,"High Park, The Junction South",2,0,54,8,10,0,1,24,1
16,"India Bazaar, The Beaches West",3,0,42,4,14,0,0,14,0
17,"Kensington Market, Chinatown, Grange Park",6,1,54,12,4,1,0,21,1
18,Lawrence Park,0,2,3,0,3,0,0,1,0
19,"Little Portugal, Trinity",2,0,51,18,6,1,0,21,1
20,"Moore Park, Summerhill East",0,0,35,1,13,1,0,9,1
21,"North Toronto West, Lawrence Park",1,0,24,1,8,0,0,11,0
22,"Parkdale, Roncesvalles",5,0,47,11,11,0,0,25,1
23,"Queen's Park, Ontario Provincial Government",6,1,62,5,4,2,0,17,3
24,"Regent Park, Harbourfront",8,0,55,6,11,3,0,16,1
25,"Richmond, Adelaide, King",15,0,45,6,11,1,0,13,9
26,Rosedale,0,0,11,0,4,0,0,5,1
27,Roselawn,0,0,13,0,3,0,0,6,0
28,"Runnymede, Swansea",2,0,50,4,6,1,0,12,1
29,St. James Town,10,0,55,7,7,1,0,15,5
30,"St. James Town, Cabbagetown",3,0,21,1,5,0,0,4,0
31,Stn A PO Boxes,8,0,42,7,14,1,0,19,9
32,Studio District,1,0,59,14,9,1,0,15,1
33,"Summerhill West, Rathnelly, South Hill, Forest...",0,0,44,2,12,1,0,13,1
34,"The Annex, North Midtown, Yorkville",10,1,55,5,8,3,0,17,1
35,The Beaches,1,0,45,8,9,0,0,16,0
36,"The Danforth West, Riverdale",2,0,58,9,8,0,0,21,2
37,"Toronto Dominion Centre, Design Exchange",17,0,38,4,12,2,0,15,12
38,"University of Toronto, Harbord",8,3,58,9,3,2,0,15,2

In [383]:
cols = [each['name'] for each in cat_list]
cols

['Arts & Entertainment',
 'College & University',
 'Event',
 'Food',
 'Nightlife Spot',
 'Outdoors & Recreation',
 'Professional & Other Places',
 'Residence',
 'Shop & Service',
 'Travel & Transport']

The total number of each venue category:

In [186]:
toronto_venues.sum()[1:]

Arts & Entertainment            204
College & University              9
Food                           1711
Nightlife Spot                  218
Outdoors & Recreation           340
Professional & Other Places      38
Residence                         1
Shop & Service                  551
Travel & Transport              116
dtype: object

We can check the number of venues in each Neighbourhood. Note this is currently supressed due to the length of the output.

In [213]:
# pd.DataFrame([toronto_venues.Neighbourhood, toronto_venues.sum(axis=1)],
#              index = ['Neighbourhood','Venues']).T.sort_values(
#                 by = 'Venues', ascending = False)

We can check the number of each venue category for a specific Neighbourhood (or Neighbourhoods)

In [214]:
toronto_venues.loc[toronto_venues.Neighbourhood == 'Lawrence Park']

,Neighbourhood,Arts & Entertainment,College & University,Food,Nightlife Spot,Outdoors & Recreation,Professional & Other Places,Residence,Shop & Service,Travel & Transport
18,Lawrence Park,0,2,2,0,3,0,0,1,0

As we can see here, most Neighbourhoods have 100 venues within 1 km. However, some areas have considerably less local venues.

## Top 5 venue categories - IS this still in use?

In [208]:
# Is this still in use?
top = toronto_venue_cats.set_index('Neighbourhood').T
top_dict = {n:top[n].sort_values(ascending=False)[0:20] for n in top}

In [211]:
# Unashamedly lazy printing:

# The ouput here is really long so is commented out temporarily

# for n in clusters:
#     print('Cluster',n,':\n')
#     for m in clusters[n]:
#         print(m,':\n')
#         for i in range(5):
#             print(top_dict[m].index[i], top_dict[m].values[i])
#         print('\n')

# As we can see above, clusters 1, 2 and 3 share very similar venue categories

In [276]:
clusters[2]

['Davisville North',
 'Dufferin, Dovercourt Village',
 'Forest Hill North & West, Forest Hill Road Park',
 'India Bazaar, The Beaches West',
 'Moore Park, Summerhill East',
 'Runnymede, Swansea',
 'Summerhill West, Rathnelly, South Hill, Forest Hill SE, Deer Park',
 'The Beaches']

In [275]:
[top_dict[n].values.sum()for n in clusters[2]]

[100, 68, 50, 76, 58, 73, 78, 77]

In [279]:
[top_dict[n] for n in clusters[3]]

[Food                           51
 Shop & Service                 14
 Outdoors & Recreation          12
 Nightlife Spot                  9
 Travel & Transport              7
 Arts & Entertainment            6
 Professional & Other Places     1
 College & University            0
 Name: Berczy Park, dtype: uint8,
 Food                           46
 Arts & Entertainment           15
 Shop & Service                 14
 Outdoors & Recreation           9
 Travel & Transport              9
 Nightlife Spot                  6
 Professional & Other Places     1
 College & University            0
 Name: Commerce Court, Victoria Hotel, dtype: uint8,
 Food                           46
 Arts & Entertainment           16
 Shop & Service                 13
 Travel & Transport             10
 Outdoors & Recreation           9
 Nightlife Spot                  5
 Professional & Other Places     1
 College & University            0
 Name: First Canadian Place, Underground city, dtype: uint8,
 Food                           44
 Outdoors & Recreation          17
 Arts & Entertainment           13
 Travel & Transport             10
 Nightlife Spot                  8
 Shop & Service                  6
 Professional & Other Places     2
 College & University            0
 Name: Harbourfront East, Union Station, Toronto Islands, dtype: uint8,
 Food                           49
 Arts & Entertainment           14
 Shop & Service                 11
 Outdoors & Recreation          10
 Travel & Transport              9
 Nightlife Spot                  6
 Professional & Other Places     1
 College & University            0
 Name: Richmond, Adelaide, King, dtype: uint8,
 Food                           43
 Shop & Service                 16
 Outdoors & Recreation          12
 Arts & Entertainment            9
 Nightlife Spot                  9
 Travel & Transport              9
 Professional & Other Places     2
 College & University            0
 Name: Stn A PO Boxes, dtype: uint8,
 Food                           42
 Arts & Entertainment           16
 Shop & Service                 13
 Travel & Transport             12
 Outdoors & Recreation          11
 Nightlife Spot                  5
 Professional & Other Places     1
 College & University            0
 Name: Toronto Dominion Centre, Design Exchange, dtype: uint8]

In [248]:
top_dict['St. James Town, Cabbagetown'].values.sum()

34

In [249]:
top_dict['St. James Town, Cabbagetown']

Food                           22
Outdoors & Recreation           5
Arts & Entertainment            3
Shop & Service                  3
Nightlife Spot                  1
College & University            0
Professional & Other Places     0
Travel & Transport              0
Name: St. James Town, Cabbagetown, dtype: uint8

In [245]:
top_dict['The Beaches'].values.sum()

77

In [247]:
top_dict['The Beaches']

Food                           43
Shop & Service                 17
Outdoors & Recreation           9
Nightlife Spot                  7
Arts & Entertainment            1
College & University            0
Professional & Other Places     0
Travel & Transport              0
Name: The Beaches, dtype: uint8

# Find way to print list of cat_vals in C1 but not C2

In [31]:
list1 = [venue_cat for venue_cat in top_dic['The Beaches'].keys() if venue_cat in list(test4['C1:_venue_cat'][0:20])]
list2 = [venue_cat for venue_cat in top_dic['The Beaches'].keys() if venue_cat in list(test4['C2:_venue_cat'][0:20])]

In [32]:
diff = np.setdiff1d(list1,list2)
diff

array(['Bar', 'Breakfast Spot'], dtype='<U19')

The fact that The Beaches has these types of venues is possibly why it is in Cluster 1

In [33]:
list1 = list(test4['C1:_venue_cat'][0:20])
list2 = list(test4['C2:_venue_cat'][0:20])
list3 = list(test4['C3:_venue_cat'][0:20])
diff = np.setdiff1d(list1,list2)
diff

array(['Bar', 'Breakfast Spot', 'Indian Restaurant', 'Mexican Restaurant',
       'Vegetarian / Vegan Restaurant'], dtype='<U29')

In [34]:
diff = np.setdiff1d(list2,list1)
diff

array(['Bank', 'Gastropub', 'Gym', 'Liquor Store', 'Spa'], dtype='<U19')

In [35]:
diff = np.setdiff1d(list1,list3)
diff

array(['Bakery', 'Bar', 'Diner', 'Indian Restaurant',
       'Italian Restaurant', 'Mexican Restaurant', 'Pharmacy', 'Pub',
       'Sandwich Place', 'Sushi Restaurant',
       'Vegetarian / Vegan Restaurant'], dtype='<U29')

In [36]:
diff = np.setdiff1d(list3,list1)
diff

array(['American Restaurant', 'Beer Bar', 'Clothing Store',
       'Concert Hall', 'Deli / Bodega', 'Gastropub', 'Gym', 'Hotel',
       'Plaza', 'Steakhouse', 'Theater'], dtype='<U19')

# Note on search radius

# Different search radii section

# Let's have alook at the top venue categories for the Brockton, Parkdale Village, Exhibition Place neighbourhood

In [39]:
top_dic['Brockton, Parkdale Village, Exhibition Place']

Restaurant                0.07
Coffee Shop               0.06
Café                      0.05
Bar                       0.05
Furniture / Home Store    0.04
Bakery                    0.03
Italian Restaurant        0.02
Indian Restaurant         0.02
Pharmacy                  0.02
Art Gallery               0.02
Theater                   0.02
Sandwich Place            0.02
Park                      0.02
Thrift / Vintage Store    0.02
Tibetan Restaurant        0.02
Smoothie Shop             0.01
Grocery Store             0.01
Soccer Stadium            0.01
Falafel Restaurant        0.01
Gym                       0.01
Name: Brockton, Parkdale Village, Exhibition Place, dtype: float64